name: CRON TEST

on:
  schedule:
    # Runs "at every minute" (see https://crontab.guru)
    - cron: '20 * * * *'

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run scripts
        run: echo Hello, world!
        run: python mnist.py